### ISSUE TITLE
Please provide a link to a screenshot (demo) of the font being used..

### ISSUE THREAD

**Issue by niyazpk** [santhoshtr/meera-tamil#9]
... so that users can immediately see what it looks like.

**Comment by sujithramani** [comment]
hello sir,
I need like above the output i got mismatched and splitted letters 

![screenshot from 2016-07-01 13 30 56](https://cloud.githubusercontent.com/assets/20064735/16516995/be7b0c9a-3f98-11e6-9cbc-70c2d6d0c112.png)

Thanks in advance
